---

- name: Playbook to install firewalld service via apt
  hosts: localhost
  become: true
  tasks:
    - name: Install firewalld on apt based linux distro
      register: fire_apt
      apt:
        name: firewalld
        state: present    #Change to state=absent in order to uninstall || Run everything via root (suos -s) or provide pswd inside inventory file
      when: ansible_os_family == "Debian" # and ansible_distribution_version == "22.04"
    
    - name: Install firewalld on yum based linux distro
      register: fire_yum
      yum:
        name: firewalld
        state: present
      when: ansible_os_family == "SUSE" or ansible_os_family == "RedHat"

    - name: Display a debug msg
      debug: msg="{{ fire_apt.stdout }}"
      when: ansible_os_family == "Debian"

    - name: Display a debug msg
      debug: msg="{{ fire_yum.stdout }}"
      when: ansible_os_family == "SUSE" or ansible_os_family == "RedHat"
  
