---
- name: Playbook to use vars & loop
  hosts: localhost
  vars:
    packages:
      - make
      - g++
      - clementine
      - vlc
      - cmake
      - lm-sensors
      - ffmpeg
  tasks:
    - name: Install a few utilities in Linux machine
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
